# Generated by Django 5.1.6 on 2025-05-07 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Searches',
            },
        ),
        migrations.RemoveField(
            model_name='landmark',
            name='user',
        ),
        migrations.RemoveField(
            model_name='meshmessage',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='meshmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='route',
            name='user',
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('src', models.CharField(default='src', max_length=100)),
                ('dest', models.CharField(default='dest', max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todolist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('complete', models.BooleanField()),
                ('todolist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.todolist')),
            ],
        ),
        migrations.DeleteModel(
            name='ConnectionLog',
        ),
        migrations.DeleteModel(
            name='Landmark',
        ),
        migrations.DeleteModel(
            name='MeshMessage',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
